name: Bug Report
description: Report a bug in Kompot
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: When I click on X, Y happens instead of Z
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (optional)
      description: How can we reproduce this?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Page URL
      description: Where did this happen?
      placeholder: https://kompot.ai/ws/contacts

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome 120, Safari 17, etc.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Drag and drop screenshots here
